server:
  port: 7474
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER_SERVICE
          uri: lb://CUSTOMER_SERVICE
          predicates:
           - Path=/customers/**
          filters:

              args:
                name: fallbackcmd
                fallbackUri: forward:/customerServiceFallBack
        - id: DEPARTMENT_SERVICE
          uri: lb://DEPARTMENT_SERVICE
          predicates:
           - Path=/departments/**
          filters:

              args:
                name: fallbackcmd
                fallbackUri: forward:/departmentServiceFallBack





hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




